#!/usr/bin/env bash
# configure a new nginx server
sudo apt-get update
sudo apt-get install -y nginx
service nginx start
sudo sed -i "21i\\\tadd_header X-served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
