#!/usr/bin/env bash
# install HAProxy
BACKEND='backend_node
        mode http
        balance roundrobin
        server 223-web-01 52.23.184.231:80 check
        server 223-web-02 54.173.122.229:80 check'
sudo add-apt-repository ppa:vbernat/haproxy-1.5 -y
sudo apt-get -y update
sudo apt-get -y dist-upgrade
sudo apt-get install -y haproxy
echo "ENABLED=1" >> /etc/default/haproxy
echo ENABLED=1 | sudo tee /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg cp_haproxy.cfg
sudo sed -i "40i\ $BACKEND" /etc/haproxy/haproxy.cfg
sudo service haproxy start
