#!/usr/bin/env bash
# install HAProxy
BACKEND='backend_node
        \n\tmode http
        \n\tbalance roundrobin
        \n\toption forwardfor
        \n\thttp-request set-header X-Forwarded-Port %[dst_port]
        \n\thttp-request add-header X-Forwarded-Proto https if { ssl_fc }
        \n\toption httpchk HEAD / HTTP/1.1\r\nHost:localhost
        \n\tserver 223-web-01 52.23.184.231:80 check
        \n\tserver 223-web-02 54.173.122.229:80 check
        \n\tserver 223-lb-01 107.22.129.214:80 check'
sudo add-apt-repository ppa:vbernat/haproxy-1.5
sudo apt-get update
sudo apt-get -y dist-upgrade
sudo apt-get install -y haproxy
echo "ENABLED=1" >> /etc/default/haproxy
echo ENABLED=1 | sudo tee /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg .
sudo touch /etc/haproxy/haproxy.cfg
echo "$BACKEND" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy start
