#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive of it.
name=$(date +%d-%m-%Y).tar.gz

mysqldump -u root -p "$1" --all-databases > backup.sql
tar -czf "$name" backup.sql 
