#!/usr/bin/env bash
# This script displays "Holberton School" ten times,for 9th iteration, say Hi
count=0
while (( count < 10 ));
do
	echo "Holberton School"
	if (( count == 8 ))
	then
		echo "Hi"
	fi
	(( count++ ))
done
