#!/usr/bin/env bash
# This script displays number from 1 to 20 and
COUNT=1
while [ $COUNT -le 20 ]
do
	case $COUNT in
		4)
		echo "bad luck from China"
		;;
		9)
		echo "bad luck from Japan"
		;;
		17)
		echo "bad luck from Italy"
		;;
	esac
		echo "$COUNT"
	(( COUNT++ ))
done
