#!/usr/bin/env bash
# Script script that configures a new Ubuntu machine to respect requirements:
#+ Install nginx on your web-01 server
#+ Nginx should be listening on port 80
#+ When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
echo "Holberton School" > /usr/share/nginx/html/index.html
sudo service nginx restart
