#!/usr/bin/env bash
# Bash Script to configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
code="error_page 404 /custom_404.html;\n location = /custom_404.html {\n\t root /usr/share/nginx/html;\n internal:\n }"
sudo touch /usr/share/nginx/html/custom_404.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sed -i "29i $code" /etc/nginx/sites-availalbe/default;
sudo service nginx restart
