#!/usr/bin/env bash
# Bash Script to configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo touch /usr/share/nginx/html/404.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sed -i "s/#error_page 404/error_page 404/g" /etc/nginx/sites-available/default
sudo service nginx restart
